### ISSUE TITLE
Group agent use cases

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-agents#3]
A group agent, aka an agentified group, is a group that has agency as-a-group beyond the agencies of any of the individual members of the group.

Here are some use cases that might explain better:
* A group makes decisions as a group.
* The group decides how it will make decisions, either as an ongoing procedure, or adhoc, decision-by-decision.
* A group decides how it will handle membership, including, but not limited to:
    * procedures for bringing in new members, such as:
        * inviting new members, which could be done by individual members or more officially by the group, but if by individual members, the group will either not interfere, or decide to allow it, or decide to prohibit the practice;
        * allowing non-members to request membership, and either accepting or rejecting such requests.
* A group makes agreements with other agents, including group and individual agents.
* The agreements made by a group survive the departure of the individuals who participated in making the agreements. If they don't, those agreements were made by some individuals, not by an agentified group.
* The history of decisions made by the group belongs to the group-as-a-whole, and also survives the departure of any of the individual members who participated in those decisions, altho the group can always subsequently rescind any of those prior decisions, except for agreements made by the group with other agents.
* In a vf-apps context, a group decides what apps it will use for what purposes. Individual members will probably need to use those apps when interacting in the context of the group.

Note: this is a starting list. Please help by suggesting improvements, making additions, or recommending deletions. I'd like to arrive at a useful list for some discussions in Holochain.

**Comment by fosterlynn** [comment]
Another set of use cases:
* Resources can be transferred from and to group agents.  Examples: exchanges, gifts, shipments (changes of location).
* Group agents can have rights and responsibilities for resources, including "ownership", "stewardship", responsibility not to lose in shipping, and others.
* Group agents can have various policies, terms, warranties, etc.  (This might be overlap with some of the above - agreements, responsibilities for resources.)

**Comment by bhaugen** [comment]
* Because a group agent is not actually alive, it needs individual agents to exercise its agency. 
* The group needs to have some way to authorize individuals to act in its capacity.
* Authorized individuals could be act for the group in more than one way, for example:
    * An individual agent who is an authorized member of the group sends a message to the group to cause the group to do something that only the group can do, for example, any of the use cases where the group does something.
    * The authorized member could act "on behalf of" the group in some context where actions "on behalf of a group" are attributed accurately to the group.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-agents/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
