### ISSUE TITLE
Degrees of agency for groups

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-agents#4]
0. A group that has no agency whatsoever.

It just exists and other agents can self-join, no permission needed. Nobody can moderate their behavior or kick them out.

**Comment by bhaugen** [comment]
1. Other agents can join only by invitation, but any member of the group can invite anybody else.

**Comment by bhaugen** [comment]
2. Membership applications need to be approved. How the approval happens is the beginning of governance for the group.

**Comment by bhaugen** [comment]
3. Member behavior is moderated. Some behaviors are not allowed, and will be stopped in some way.

**Comment by bhaugen** [comment]
4. Members may be kicked out for bad behavior.

**Comment by bhaugen** [comment]
5. The group may make agreements with other agents, including other group agents.

**Comment by bhaugen** [comment]
6. Group agreements survive the departure of the members who originally made the agreements. 

At this stage, the group has full agency. (But anything past degree 0 implies some degree of group agency.)

**Comment by bhaugen** [comment]
Please let me know if you think any of this progression is wrong, or incorrectly sequenced, or if other degrees of agency should be added.

**Comment by mayel** [comment]
Could you clarify if you're talking about technical limitations, programmatically imposed rules, or simply social agreements around how a group should function? 

Because apart from certain implementations of cryptographic and distributed apps, the programmers and ultimately the server operators (and further, their ISPs and the governments/courts with power over them) can change and/or at least partially override any such rules. One reason online groups have rules and moderation is precisely to deal with issues among themselves rather than have them escalated and imposed...

**Comment by bhaugen** [comment]
> Could you clarify if you're talking about technical limitations, programmatically imposed rules, or simply social agreements around how a group should function?
> 

Social agreements which might want to be implemented in group software. Or whether a given group should be classified as an agent or not. And ultimately how group agency should be implemented in software, which is an issue in Holochain and will probably become an issue in CommonsPub as well.

One angle on group agency is a group's agency can't be exercised by the group, it must be exercised by some individuals or software created and deployed for the group by some individuals.

But a group could have a bot that gets triggered by some authorized individuals or authorized code that takes actions on behalf of the group.

Some people in Holochain and other groups did not believe that groups should have any agency at all. Which would mean that a group could not have any of those degrees of agency listed above.

Am I making sense yet?

**Comment by bhaugen** [comment]
This is the first thing I read about group agents, quite a few years ago:
http://www.jamesodell.com/Odell-AOSE04.pdf

Bill McCarthy and I met Odell in the early 2000's and had a long conversation about REA Agents and Odell Agents.

**Comment by bhaugen** [comment]
P.S. "authorized individuals or code" requires some degree of group governance, which could be a BDFL or something like Loomio-style voting.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-agents/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
